services:
  frontend:
    # フロントエンドサービスのビルド設定
    build:
      context: . # Dockerfile のビルドコンテキスト（プロジェクトのルートディレクトリ）
      dockerfile: ./docker/Dockerfile.front.dev # 使用する Dockerfile のパス

    # ホストマシンとコンテナ間でディレクトリを共有（リアルタイム同期）
    volumes:
      - ./frontend:/app # ホストの ./frontend をコンテナの /app にマウント

    # ホストとコンテナのポートをマッピング
    ports:
      - "3000:3000" # ホストの 3000 番ポートをコンテナの 3000 番ポートにマッピング

    # コンテナ起動時に実行するコマンド
    command: npm run dev # 開発サーバーを起動
