services:
 # サービス名．これをサービス名と同じにしないと設定がうまく反映されない
  frontend:
    build:
    # Dockerfileのあるディレクトリを指定(基本，作業ディレクトリを指定)
      context: ./frontend
      dockerfile: ./../Dockerfile
    tty: true
    volumes:
      - ./frontend/src:/front_app/src

    # ホットリロードの有効化
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
    # 左は自分のPCのポート、右はdockerコンテナ内のポート
    ports:
      - "4000:3000"

  # back: